version: 2.1

commands:
  install_python_requirements:
    description: "Install python requirements"
    parameters:
      folder:
        type: string
        default: ""
    steps:
      - run:
          name: Install python requirements
          command: |
            cd << parameters.folder >>
            if test -e requirements.txt; then
              echo "Installing python requirements"
              pip install -r requirements.txt
            fi
  run_pylint:
    description: "Run pylint on a list of files"
    parameters:
      folder:
        type: string
        default: ""
      file_list:
        type: string
        default: "files_for_pylint.lst"
    steps:
      - run:
          name: Install pylint
          command: pip install pylint
      - run:
          name: Run pylint
          command: |
            cd << parameters.folder >>
            echo "Running pylint"
            if test -e << parameters.file_list >>; then
              echo "Running pylint"
              for f in $(cat << parameters.file_list >>); do
                pylint --ignore-docstrings y --ignore-comments y --indent-string '  ' "--disable=C0116" $f || true
              done
            fi
