version: 2.1

jobs:
  run_operations:
    docker:
      - image: cimg/python:3.13
    resource_class: small
    parameters:
      folder:
        type: string
    steps:
      - checkout
      - run: 
          name: Install python requirements
          command: |
            ls
            echo $FOLDER
            cd ${FOLDER}
            pwd
            pip install -r requirements.txt
      - run:
          name: Run operations for ${FOLDER}
          command: |
            echo "Running operations for ${FOLDER}"
            cd ${FOLDER}
            pylint --ignore-docstrings y --ignore-comments y --indent-string '  ' "--disable=C0116" add_book.py
workflows:
  detect_and_run:
    jobs:
