version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1.0.0

executors:
  python:
    docker:
      - image: circleci/python:3.8
  base:
    docker:
      - image: cimg/base:2024.12


jobs:
  setup:
    executor: base
    resource_class: small
    steps:
      - checkout
      - run:
          name: Check for changed folders with .py files
          command: |
            set -e

            # Handle errors from git diff
            changed_dirs=$(git diff --name-only HEAD~1 HEAD 2>/dev/null || echo "")
            
            echo "[Check for changed folders with .py files] Git diff"
            git diff --name-only HEAD~1 HEAD 2>/dev/null || echo ""
            echo "[Check for changed folders with .py files] Changed dirs: ${changed_dirs}"

            if [ -z "$changed_dirs" ]; then
              echo "Error: git diff command failed or no changes found."
              circleci-agent step halt
            fi

            changed_dirs=$(echo "$changed_dirs" | grep '/' | xargs -n1 dirname | sort | uniq)
            py_dirs=""
            for dir in $changed_dirs; do
              if ls $dir/*.py 1> /dev/null 2>&1; then
                py_dirs="$py_dirs $dir"
              fi
            done
            if [ -z "$py_dirs" ]; then
              echo "No directories with .py files changed. Stopping build."
              circleci-agent step halt
            else
              echo "Found directories with .py files: $py_dirs"
              # Exporting the directories for the next job
              echo "export PY_DIRS=\"$py_dirs\"" >> $BASH_ENV
            fi
      - run:
          name: Generate dynamic config
          command: |
            ls -la
            chmod +x generate_dynamic_config.sh
            ./generate_dynamic_config.sh
      - continuation/continue:
          configuration_path: .circleci/generated_config.yml
          parameters: '{}'

workflows:
  setup-workflow:
    jobs:
      - setup