version: 2.1

commands:
  install_python_requirements:
    description: "Install python requirements"
    parameters:
      folder:
        type: string
        default: ""
    steps:
      - run:
          name: [<< parameters.folder >>] Install python requirements
          command: |
            cd << parameters.folder >>
            if test -e requirements.txt; then
              echo "Installing python requirements"
              pip install -r requirements.txt
            fi
  run_pylint:
    description: "Run pylint on a list of files"
    parameters:
      folder:
        type: string
        default: ""
      file_list:
        type: string
        default: "files_for_pylint.lst"
    steps:
      - run:
          name: [<< parameters.folder >>] Install pylint
          command: pip install pylint
      - run:
          name: [<< parameters.folder >>] Run pylint
          command: |
            cd << parameters.folder >>
            echo "Running pylint"
            if test -e << parameters.file_list >>; then
              for f in $(cat << parameters.file_list >>); do
                echo "Running pylint for $f"
                pylint --ignore-docstrings y --ignore-comments y --indent-string '  ' "--disable=C0116" $f || true
              done
            fi


jobs:
  run_operations:
    docker:
      - image: cimg/python:3.13
    resource_class: small
    parameters:
      folder:
        type: string
    steps:
      - checkout
      - install_python_requirements:
          folder: << parameters.folder >>
      - run_pylint:
          folder: << parameters.folder >>
          file_list: "files_for_pylint.lst"
      - run:
          name: [<< parameters.folder >>] Run operations
          command: |
            echo "Running operations for << parameters.folder >>"
            cd << parameters.folder >>
            ls

workflows:
  setup_and_run_operations:
    jobs:
