version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@1.0.0

executors:
  python:
    docker:
      - image: circleci/python:3.8
  base:
    docker:
      - image: cimg/base:2024.12


jobs:
  setup:
    executor: base
    steps:
      - checkout
      - run:
          name: Check for changed folders with .py files
          command: |
            changed_folders=$(git diff --name-only HEAD~1 HEAD | grep -E '.*\.py$' | xargs -n1 dirname | sort | uniq)
            if [ -z "$changed_folders" ]; then
               echo "No folders with .py files changed. Stopping build."
               circleci-agent step halt
            fi
      - run:
          name: Generate dynamic config
          command: |
            ls -la
            chmod +x generate_dynamic_config.sh
            ./generate_dynamic_config.sh
      - continuation/continue:
          configuration_path: .circleci/generated_config.yml
          parameters: '{}'

workflows:
  version: 2
  setup-workflow:
    jobs:
      - setup