version: 2.1

jobs:
  run_operations:
    docker:
      - image: cimg/python:3.13
    resource_class: small
    parameters:
      folder:
        type: string
    steps:
      - checkout
      - run: 
          name: Install python requirements
          command: |
            ls
            echo << parameters.folder >>
            cd << parameters.folder >>
            pwd
            pip install -r requirements.txt
      - run:
          name: Run operations for << parameters.folder >>
          command: |
            echo "Running operations for << parameters.folder >>"
            cd << parameters.folder >>
            pylint --ignore-docstrings y --ignore-comments y --indent-string '  ' "--disable=C0116" add_book.py || true
workflows:
  setup_and_run_operations:
    jobs:
