version: 2.1

orbs:
  my-commands: local!/.circleci/commands.yml
  
jobs:
  run_operations:
    docker:
      - image: cimg/python:3.13
    resource_class: small
    parameters:
      folder:
        type: string
    steps:
      - checkout
      - install_python_requirements:
          folder: << parameters.folder >>
      - run_pylint:
          folder: << parameters.folder >>
          file_list: "files_for_pylint.lst"
      - run:
          name: Run operations for << parameters.folder >>
          command: |
            echo "Running operations for << parameters.folder >>"
            cd << parameters.folder >>
            ls

workflows:
  setup_and_run_operations:
    jobs:
