version: 2.1

setup: true

jobs:
  detect-changes:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: "Find Changed Folders"
          command: |
            # Detect changed folders
            changed_folders=$(git diff --name-only HEAD^ HEAD | xargs -n1 dirname | sort -u)
            # Save as JSON array
            echo "$changed_folders" | jq -R -s -c 'split("\n")[:-1]' > changed_folders.json
      - persist_to_workspace:
          root: .
          paths:
            - changed_folders.json

  run-tests:
    docker:
      - image: circleci/python:3.9
    parameters:
      folder:
        type: string
    steps:
      - run:
          name: "Run Tests"
          command: |
            echo "Running tests in folder: << parameters.folder >>"

workflows:
  dynamic-matrix:
    jobs:
      - detect-changes
      - run-tests:
          matrix:
            parameters:
              folder: << pipeline.parameters.changed_folders >>
