version: 2.1

executors:
  python:
    docker:
      - image: cimg/python:3.13
  base:
    docker:
      - image: cimg/base:2024.12

jobs:
  run_operations:
    executor: python
    resource_class: small
    parameters:
      folder:
        type: string
    steps:
      - checkout
      - run: 
          name: Install python requirements
          command: |
            cd $FOLDER
            pip install -r requirements.txt
      - run:
          name: Run operations for $FOLDER
          command: |
            echo "Running operations for $FOLDER"
            cd $FOLDER
            pylint --ignore-docstrings y --ignore-comments y --indent-string '  ' "--disable=C0116" add_book.py
workflows:
  detect_and_run:
    jobs: