version: 2.1

orbs:
  python: circleci/python@2.1.1

parameters:
  changed_dirs:
    type: string
    default: "[]"

jobs:
  pylint_check:
    parameters:
      folder:
        type: string
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run pylint on << parameters.folder >>
          command: |
            pip install pylint
            pylint << parameters.folder >>/*.py

workflows:
  pylint_checks:
    jobs:
      - pylint_check:
          matrix:
            parameters:
              #folder: << pipeline.parameters.changed_dirs >>
              folder: ["folder1", "folder2"]