version: 2.1

parameters:
  changed_dirs:
    type: string
    default: '{ "folder": ["folder1", "folder2"]}'

jobs:
  pylint_check:
    parameters:
      folder:
        type: string
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Run pylint on << parameters.folder >>
          command: |
            echo $FOLDER
            #pylint << parameters.folder >>/*.py

workflows:
  pylint_checks:
    jobs:
      - pylint_check:
          matrix:
            parameters: << pipeline.parameters.changed_dirs >>
              #folder: << pipeline.parameters.changed_dirs >>
              #folder: << pipeline.parameters.changed_dirs >>